services:

  db:
    container_name: shakcommerce_postgres
    image: postgres:16-alpine3.20
    env_file:
      - .env
    ports:
      - "5572:5432"
    volumes:
      - ./db_backup:/var/lib/postgresql/data
    restart: always

  django:
    container_name: shakcommerce_django
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/app
    command: >
      sh -c "python /app/manage.py collectstatic --noinput &&
      python /app/manage.py makemigrations && python /app/manage.py migrate && 
      python /app/manage.py init_admin &&
      gunicorn shakcommerce.wsgi --workers 3 --threads 8 --timeout 240 --bind 0.0.0.0:8000  --reload  --chdir /app/"
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
